### ISSUE TITLE
Handle partial order cancellations

### ISSUE THREAD

**Issue by CydeWeys** [gbrodman/order-tracking#108]
The price displayed in the reconciliation spreadsheet reflects the original total cost of the order, even if items in the order have subsequently been canceled. This requires manual reconciliation.

It would be nice if the script could read the cancellation emails and update the total billed cost.  Admittedly that might be a little bit difficult because the cost of the items cancelled isn't sent in the email -- so possibly then just flag orders that have cancellations?

**Comment by gbrodman** [comment]
this is now flagged, in the cancelled items column
