### ISSUE TITLE
MYS issues

### ISSUE THREAD

**Issue by figgarro** [gbrodman/order-tracking#113]
I keep getting this when running , get_tracking_numbers.py
**Could not find order management for group mysbuyinggroup**
and this error when running reconcile.py
**Received exception when getting costs: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pf-search-button"}
  (Session info: headless chrome=78.0.3901.0)**

**Comment by gbrodman** [comment]
Double check the username and password?

**Comment by figgarro** [comment]
That was it, a stray ' will do it.

**Comment by CydeWeys** [comment]
It would be possible at least to display a better error message in the case that the account credentials are inaccurate.  It pops up a message saying "Sorry, your credentials are invalid" that WebDriver could look for.  Might be worth it for SellerSpeed, because so many sites use it.
