### ISSUE TITLE
Add a get_tracking mode to re-process read "has shipped" emails

### ISSUE THREAD

**Issue by CydeWeys** [gbrodman/order-tracking#118]
Periodically I go through and label batches of "has shipped" emails as unread and run the get_tracking script on them again.  Surprisingly, this often comes back with a new tracking # that wasn't yet known to the script.  I don't know why.  Perhaps it had some kind of error initially in loading the email?  Maybe Amazon wasn't properly displaying a tracking #?  Perhaps the tracking # has changed on the order and the initial one isn't shipping?  (This does happen occasionally.)  Or perhaps I screwed up and accidentally clicked on a "has shipped" email without realizing it, thus marking it as read and causing the script to ignore it.

Whatever the cause, the result is dangerous.  It would be good to have a mode on the get_tracking script I could run over night that would go back through all "has shipped" emails again, including the read ones, and upload them to catch any stragglers.  This mode would likely have to run at a reduced rate to avoid Amazon CAPTCHAs, hence running it over night.

**Comment by gbrodman** [comment]
This is done, right?
