### ISSUE TITLE
Add to cart URL when sending instock email

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#119]
When an in stock email is received, do the following:

1. Create an add to cart link per item
2. Create an add to cart link for all items

**Comment by nunyabiz1982** [comment]
make them smile links

**Comment by gbrodman** [comment]
other improvements
- potentially include a price N where we don't notify unless the price is <= N
- try to grab all items at once, to make it just have one page load instead of N page loads

**Comment by gbrodman** [comment]
also send to all recipients at once to avoid any potential issues with spam detection

**Comment by gbrodman** [comment]
add logging

add option to run indefinitely

**Comment by gbrodman** [comment]
All done. --run-indefinitely sleeps for five minutes then re-runs.
