### ISSUE TITLE
check "verified" checkboxes in melul portals

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#120]
if the verified checkbox isn't checked, we shouldn't count that tracking as having a checked-in cost

**Comment by nunyabiz1982** [comment]
huh?

**Comment by nunyabiz1982** [comment]
are you talking about damaged items?

**Comment by gbrodman** [comment]
whatever reason it's not checked--the reasons vary

**Comment by gbrodman** [comment]
similar to #98, so will just include it there
