### ISSUE TITLE
USA Reconcile: Unable to locate element: id="filter-none"

### ISSUE THREAD

**Issue by neocryptek** [gbrodman/order-tracking#136]
Getting this error on "Loading group usa" when trying to run reconcile:
`Received exception when getting costs: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="filter-none"]"}`

Retries 5 times with the same error. Seems to always be when trying to load the 25th USA PO number. Has been doing it for a few days now. Not sure if they changed their website?

This causes the entire reconciliation process to error out and not generate any reports for the other groups.

**Comment by gbrodman** [comment]
please pull the most recent version of the code

**Comment by gbrodman** [comment]
it should be fixed in more recent versions, USA changed their site

**Comment by neocryptek** [comment]
Fixed!
