### ISSUE TITLE
Try to include expected delivery dates

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#150]
there are a few different types of email, but we should probably just have the last one like we do for ship_date? We'll have to parse the dates which isn't the worst

**Comment by nunyabiz1982** [comment]
Why don't you just use the timestamp of the gmail email?

**Comment by gbrodman** [comment]
delivery dates

**Comment by nunyabiz1982** [comment]
oh yeah, i'm smoking crack

**Comment by nunyabiz1982** [comment]
why not just use the ups/fedex/usps apis for part of this? (assuming they have)

**Comment by gbrodman** [comment]
more complicated to write against 2+ new apis, that would require new accounts

**Comment by gbrodman** [comment]
this is done for trackings picked up from now on
