### ISSUE TITLE
Need to handle expired tracking emails

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#18]
There are certain cases when amazon tracking links no longer provide tracking data.  The ones that i know are:

1. After a certain amount of time, amazon removes the tracking data.  I'm not sure how long this is after the order is shipped

2.After an account lock, orders that are open get canceled.  Sometimes these end up shipping and that tracking info is lost

Would be good to know of these somehow as well.  Maybe export a failed list?

**Comment by gbrodman** [comment]
In (2), does one still receive emails? 

For (1), I think the best solutions is to have this only search in the last month or two

**Comment by gbrodman** [comment]
we should be good here, I think
