### ISSUE TITLE
Ignore non-group shipping notifications

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#19]
Just had a failure on a shipment to home where the seller was non-Amazon and it failed. We should ignore non-group emails

**Comment by nunyabiz1982** [comment]
Can you clarify this?  It was an email from az but the seller was 3rd party?

**Comment by gbrodman** [comment]
yep -- this won't happen with buying group emails but it could happen on random crap that you order to your home

**Comment by nunyabiz1982** [comment]
Ok, so I actually buy for someone that often buys some 3rd party stuff....

**Comment by gbrodman** [comment]
:( 

ok then really the solution here is to have a better "ignore email" functionality

**Comment by gbrodman** [comment]
if we ignore emails, print out the subject or something so it's easier to debug

**Comment by gbrodman** [comment]
We now print an error message if we can't find the group, but we mark that email as unread and continue on. 

TODO: Do the same if something else fails

**Comment by gbrodman** [comment]
should be good here, will continue on if tracking ID lookup fails
