### ISSUE TITLE
Rate-limiting by Amazon

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#26]
After a few hundred tracking number URLs, we got captcha'ed -- if this happens, we should somehow communicate to the user to take a break

**Comment by nunyabiz1982** [comment]
"take a break", stop script and come back a few hours later and continue where we left off :-)

**Comment by gbrodman** [comment]
We now have exponential backoff retry (thanks Ben) so this is probably about as good as we're going to get here. I also haven't seen this in a while, even when running over about 350 trackings. Closing.
