### ISSUE TITLE
Add total paid per tracking/order to google sheet

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#34]
Need to grab total paid for all the items attached to a particular tracking and order to google sheets.  Most people I assume reconcile by making sure the amazon order total matches what the buy group pays for all the tracking #s of that particular order.  Need to work around issues such as more than one order send with same tracking.

**Comment by nunyabiz1982** [comment]
actually, order total is preferred, not per tracking

**Comment by gbrodman** [comment]
This is already done with the reconciliation task, where we push all the order totals to Sheets
