### ISSUE TITLE
Must be able to see item name in google sheets

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#35]
I know amazon doesn't provide a way to see item name so here are a few ideas I had:

1.)ability to upload an amazon report excel and match up the data
2.)ability to pull the item info from portal after checkin.  This option seems easy but doesn't work if the bg doesn't have a portal

**Comment by gbrodman** [comment]
FYI: this will show up very messy but it'll appear in the Trackings tab, along with the reimbursed cost if one exists. We pull it from the Amazon shipping email for business shipments so it won't always be there
