### ISSUE TITLE
Ability to sort sheet columns to my preference 

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#36]
Give the user the ability to put column orders as they prefer

**Comment by gbrodman** [comment]
this is probably not going to happen since it makes uploading new orders significantly more complicated (like, what if we change the order halfway through, etc)

**Comment by gbrodman** [comment]
I'm going to say that this won't happen because it's not really possible with the process of uploading collections of objects to Sheets.
