### ISSUE TITLE
Write out info to a Google Sheet

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#4]
Use tracking # for primary key (so that it's idempotent), probably have one spreadsheet per buying group

**Comment by gbrodman** [comment]
and also potentially tracking status using something like https://www.ups.com/upsdeveloperkit?loc=en_US

**Comment by gbrodman** [comment]
Done partially in #13 

TODO:
- Don't write out the same tracking # multiple times in multiple runs
- Look into UPS/USPS/Fedex integration

**Comment by mvpjsand** [comment]
Need to add the name of the specific buy group to the sheet.  And would be great to know if this is shipped to home or to bg warehouse.  Can we add to an existing sheet or is this too much?

**Comment by gbrodman** [comment]
Are you thinking of having all tracking numbers in one tab/sheet? If the orders are split up by group  / tab, then that should probably be unnecessary right?

**Comment by gbrodman** [comment]
we should be good here
