### ISSUE TITLE
Add shipping date as column in Google Sheet

### ISSUE THREAD

**Issue by CydeWeys** [gbrodman/order-tracking#47]
Shouldn't be too hard to extract this from either the timestamp on the email itself or the information on the tracking page, and it would be useful to have in that you could e.g. use it to sort the spreadsheet, and see the oldest shipped order that hasn't yet been checked in.

In the case of clustering, this could just be the earliest shipped date out of any part of the order (rather than trying to turn it into a list).

**Comment by nunyabiz1982** [comment]
Could you add order date too?

**Comment by gbrodman** [comment]
This is done -- the tracking object in the sheet now includes ship date (it'll be properly filled going forward)
