### ISSUE TITLE
Use optional Google Drive for object storage

### ISSUE THREAD

**Issue by gbrodman** [gbrodman/order-tracking#64]
We currently save some things on disk which is fine but unreliable.

**Comment by nunyabiz1982** [comment]
Awesome

**Comment by gbrodman** [comment]
another benefit of this would be that you could run the scripts from different computers and it ~*~*~*~*just work*~*~*~*~

**Comment by gbrodman** [comment]
This is done -- one will need to enable the drive API for their Cloud project (similar to enabling the Sheets API that we've already done), create a folder in Drive, and provide the folder ID in the config (check the template for where).
