### ISSUE TITLE
Best Buy Support

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#7]
Ability to get best buy order/tracking details from emails

**Comment by gbrodman** [comment]
I thought about this and it'd be a good addition, the main difficulty is the situation where Best Buy doesn't include the full tracking number in their emails (USPS numbers)

Normally you'd be able to just click on the link like for Amazon, but BB's system is buggy and it appears like it doesn't always take you to the order page for guest / random-account orders

**Comment by nunyabiz1982** [comment]
Can we skip USPS for now and address in the future? Seems to be that majority of BB stuff goes through USPS.

**Comment by gbrodman** [comment]
This is done. We track Best Buy unread shipping emails just like we track unread Amazon shipping emails, and we treat the orders  the same way, including cost retrieval and clustering.
